# Generated by Django 4.0.5 on 2022-06-30 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(default='fbvsdfk', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
